WHENEVER SQLERROR EXIT FAILURE ROLLBACK
WHENEVER OSERROR EXIT FAILURE ROLLBACK
SET ECHO OFF VERIFY OFF FEEDBACK ON

-- Disable management-pack access in the disposable integration database.
ALTER SYSTEM SET CONTROL_MANAGEMENT_PACK_ACCESS = 'NONE' SCOPE = BOTH;
ALTER SESSION SET CONTAINER = ORCLPDB1;

CREATE USER SBYORACLE_TEST IDENTIFIED BY "&1" QUOTA 10M ON USERS;
GRANT CREATE SESSION, CREATE TABLE TO SBYORACLE_TEST;

-- DISPLAY_CURSOR requires direct grants, including its underlying fixed views.
GRANT SELECT ON SYS.V_$SQL TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$SQL_PLAN TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$SQL_PLAN_STATISTICS_ALL TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$SESSION TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$SQL_OPTIMIZER_ENV TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$SQL_BIND_CAPTURE TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$SQL_SHARED_CURSOR TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$SQL_CS_SELECTIVITY TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$SQL_CS_STATISTICS TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$INSTANCE TO SBYORACLE_TEST;
GRANT SELECT ON SYS.V_$PARAMETER TO SBYORACLE_TEST;
GRANT EXECUTE ON SYS.DBMS_XPLAN TO SBYORACLE_TEST;
GRANT EXECUTE ON SYS.DBMS_LOB TO SBYORACLE_TEST;
GRANT EXECUTE ON SYS.DBMS_STATS TO SBYORACLE_TEST;

-- A second user verifies the report's behavior without diagnostic privileges.
CREATE USER SBYORACLE_LIMITED IDENTIFIED BY "&1";
GRANT CREATE SESSION TO SBYORACLE_LIMITED;

-- No SQL Monitoring view or package grants are introduced by this script.
EXIT SUCCESS
